apiVersion: v1 
kind: Service
metadata:
  name: springbootapp-service
  labels:
    name: springbootapp
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  selector:
    name: springbootapp
    tier: frontend