apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SriSatyaPothala/SpringbootApp-Jenkins-ArgoCd.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: myspringbootapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
